language: rust
rust: nightly
sudo: false
install:
  - .travis/docs/install
script: 
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc
after_success:
  - .travis/docs/after_success
